defmodule OrchidStratum.BypassHook do
  @behaviour Orchid.Runner.Hook

  alias OrchidStratum.HashKeyBuilder

  @spec call(Orchid.Runner.Context.t(), Orchid.Runner.Hook.next_fn()) ::
          Orchid.Runner.Hook.hook_result()
  def call(ctx, next_fn) do
    is_cacheable = Keyword.get(ctx.step_opts, :cache, false)

    # Put global content into workflow ctx
    meta_store_config = Orchid.WorkflowCtx.get_baggage(ctx.workflow_ctx, :meta_store)
    blob_store_config = Orchid.WorkflowCtx.get_baggage(ctx.workflow_ctx, :blob_store)

    case {is_cacheable, meta_store_config, blob_store_config} do
      {true, {meta_mod, _meta_options}, {blob_mod, _blob_options}} ->
        process_hash(ctx, next_fn, meta_mod, blob_mod)

      _ ->
        next_fn.(ctx)
    end
  end

  defp process_hash(ctx, next_fn, meta_mod, blob_mod) do
    cache_used_key = Keyword.get(ctx.step_opts, :cache_keys, [])

    step_key =
      HashKeyBuilder.step_key(ctx.step_implementation, ctx.inputs, ctx.step_opts, cache_used_key)

    with {:ok, cached_outputs} <- apply(meta_mod, :get, [step_key]),
         true <- all_blobs_exist?(cached_outputs, blob_mod) do
      build_hit_context(ctx, cached_outputs, blob_mod)
    else
      # miss or false
      _ -> execute_and_hash(ctx, next_fn, meta_mod, blob_mod, step_key)
    end
  end

  defp all_blobs_exist?(cached_outputs, blob_mod) do
    cached_outputs |> IO.inspect()

    Enum.all?(cached_outputs, fn %{content_hash: hash} ->
      if function_exported?(blob_mod, :blob_exists?, 1) do
        apply(blob_mod, :blob_exists?, [hash])
      else
        match?({:ok, _}, apply(blob_mod, :blob_get, [hash]))
      end
    end)
  end

  # Code generated by Gemini without mannual verify
  defp build_hit_context(ctx, cached_outputs, blob_mod) do
    # Return context with outputs populated as lightweight references
    refs =
      Enum.map(cached_outputs, fn %{name: name, content_hash: hash} ->
        %{__struct__: Orchid.Param} =
          Enum.find(ctx.inputs, &(&1.name == name)) || %{__struct__: Orchid.Param}

        # Reconstruct the output param without loading the actual data
        struct(Orchid.Param, name: name, payload: {:ref, blob_mod, hash})
      end)

    {:ok, refs}
  end

  defp execute_and_hash(ctx, next_fn, meta_mod, blob_mod, step_key) do
    # Hydrate inputs
    hydrated_inputs =
      case ctx.inputs do
        %Orchid.Param{} = input -> hydrate_param(input, blob_mod)
        inputs -> Enum.map(inputs, &hydrate_param(&1, blob_mod))
      end

    next_fn.(%{ctx | inputs: hydrated_inputs})
    |> case do
      {:ok, res} ->
        # Store with step_key
        {dehydrated_outputs, meta_outputs} =
          case res do
            %Orchid.Param{} = output ->
              dehydrate_param(output, blob_mod)

            outputs ->
              Enum.map_reduce(outputs, [], fn param, acc_meta ->
                {ref_param, meta_entry} = dehydrate_param(param, blob_mod)
                {ref_param, [meta_entry | acc_meta]}
              end)
          end

        meta_entry = %{
          outputs: Enum.reverse(meta_outputs),
          created_at: System.system_time(:millisecond)
        }

        apply(meta_mod, :meta_put, [step_key, meta_entry])

        {:ok, dehydrated_outputs}

      err_or_special ->
        err_or_special
    end
  end

  defp hydrate_param(%Orchid.Param{payload: {:ref, store_mod, hash}} = param, _blob_mod) do
    case store_mod.blob_get(hash) do
      {:ok, data} ->
        %{param | payload: data}

      :miss ->
        # If upstream data is missing during hydration, we must fail.
        # This implies a severe cache consistency issue globally.
        raise "Hydration failed! Blob #{inspect(hash)} missing from #{inspect(store_mod)}"
    end
  end

  # Already hydrated
  defp hydrate_param(param, _blob_mod), do: param

  defp dehydrate_param(%Orchid.Param{name: name, payload: payload} = param, blob_mod) do
    # If it's somehow already a ref (e.g., a pass-through step), skip hashing
    case payload do
      {:ref, ^blob_mod, hash} ->
        {param, %{name: name, content_hash: hash}}

      _actual_data ->
        hash = HashKeyBuilder.payload_hash(payload)
        :ok = blob_mod.blob_put(hash, payload)

        ref_param = %{param | payload: {:ref, blob_mod, hash}}
        meta_entry = %{name: name, content_hash: hash}

        {ref_param, meta_entry}
    end
  end
end
